CREATE DATABASE IF NOT EXISTS mythconvergdn26;
GRANT ALL ON mythconvergdn26.* TO dn26@localhost IDENTIFIED BY "mythtv";
FLUSH PRIVILEGES;
GRANT CREATE TEMPORARY TABLES ON mythconvergdn26.* TO dn26@localhost IDENTIFIED BY "mythtv";
FLUSH PRIVILEGES;
ALTER DATABASE mythconvergdn26 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
